version: "3"

services:

  # web:
  #   image: nginx:latest
  #   container_name: web
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./.docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: app
    build:
      dockerfile: ./.docker/php/Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # redis: TO DO