version: "3"

services:

  # web:
  #   image: nginx:latest
  #   container_name: web
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./.docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: app
    build:
      dockerfile: ./.docker/php/Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # db:
  #   tty: true
  #   image: mysql:latest
  #   container_name: "${DB_NAME}"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./.docker/db:/var/lib/mysql

  # redis: TO DO